### ISSUE TITLE
Create the "Contact Us" page

### ISSUE THREAD

**Issue by Shantanu993** [vibinex/vibinex-server#402]
The website doesn't have any contact us page yet.
We need to develop a "Contact Us" page for the Vibinex website. This page will provide visitors with various ways to get in touch with you.

The page would have following features and more custom ones could be added:

- A Contact form for user inquiries.
- Provide relevant contact information, including email addresses, social media links, and physical address, etc.
- User friendly design

Below is a sample design, please suggest the changes necessary.
![Contact Us](https://github.com/user-attachments/assets/f6ae8ac7-53c3-435e-b239-d20cd2f61f6d)

**Comment by avikalpg** [comment]
We don't need a separate "Contact Us" page on our website. The email address, phone number, Discord channel and Calendly link are all provided in the footer of the website. 

However, we do have an open pull request related to the creation of a contact form instead of having the Calendly link for the "Book demo" button on the landing page of the website: #201 
If you are interest, you can pick that up and complete it.
